name: Release
on:
  workflow_dispatch:

jobs:
  release-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup | Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        target: wasm32-unknown-unknown

    - uses: jetli/trunk-action@v0.4.0
      with:
        # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
        version: 'latest'

    # Install cargo deps
    - name: Trunk build
      run: |
        trunk build --release --public-url /vong/

    # Deploy, GitHub Pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
